In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.21.5'

In [3]:
%%capture
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [4]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [5]:
# Who are the most popular car manufacturers (top-3) according to the dataset?
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [6]:
df.Make = df.Make.astype('str')

In [7]:
df.nunique()

Make                   48
Model                 915
Year                   28
Engine Fuel Type       10
Engine HP             356
Engine Cylinders        9
Transmission Type       5
Driven_Wheels           4
Number of Doors         3
Market Category        71
Vehicle Size            3
Vehicle Style          16
highway MPG            59
city mpg               69
Popularity             48
MSRP                 6049
dtype: int64

In [8]:
df.Make.describe()

count         11914
unique           48
top       Chevrolet
freq           1123
Name: Make, dtype: object

In [9]:
df.groupby('Make').count()

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                        
Acura            252   252               252        252               252   
Alfa Romeo         5     5                 5          5                 5   
Aston Martin      93    93                93         93                93   
Audi             328   328               328        328               328   
BMW              334   334               334        334               334   
Bentley           74    74                74         74                74   
Bugatti            3     3                 3          3                 3   
Buick            196   196               196        196               196   
Cadillac         397   397               397        397               397   
Chevrolet       1123  1123              1123       1117              1121   
Chrysler         187   187               187        187               187   
Dodge            626   626               626        626               626   
FIAT              62    62                62         59                62   
Ferrari           69    69                69         69                69   
Ford             881   881               881        868               881   
GMC              515   515               515        515               515   
Genesis            3     3                 3          3                 3   
HUMMER            17    17                17         17                17   
Honda            449   449               449        447               449   
Hyundai          303   303               303        303               303   
Infiniti         330   330               330        330               330   
Kia              231   231               231        226               231   
Lamborghini       52    52                52         52                52   
Land Rover       143   143               143        143               143   
Lexus            202   202               202        202               202   
Lincoln          164   164               164        156               164   
Lotus             29    29                29         29                29   
Maserati          58    58                58         58                58   
Maybach           16    16                16         16                16   
Mazda            423   423               423        423               403   
McLaren            5     5                 5          5                 5   
Mercedes-Benz    353   353               353        352               353   
Mitsubishi       213   213               213        212               210   
Nissan           558   558               558        548               558   
Oldsmobile       150   150               150        150               150   
Plymouth          82    82                82         82                82   
Pontiac          186   186               186        186               186   
Porsche          136   136               136        136               136   
Rolls-Royce       31    31                31         31                31   
Saab             111   111               111        111               111   
Scion             60    60                60         60                60   
Spyker             3     3                 3          3                 3   
Subaru           256   256               256        256               256   
Suzuki           351   351               348        351               351   
Tesla             18    18                18          0                18   
Toyota           746   746               746        744               745   
Volkswagen       809   809               809        809               805   
Volvo            281   281               281        281               281   

               Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                               
Acura                       

In [10]:
df.Make.value_counts(ascending=False)

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [11]:
# Number of unique Audi car models

df[(df.Make == 'Audi')].nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [12]:
# Number of columns with missing values
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [13]:
#Does the median value change after filling missing values
df['Engine Cylinders'].median()

6.0

In [14]:
df['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [15]:
df['Engine Cylinders'].fillna(value=6)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [16]:
df['Engine Cylinders'].median(
)

6.0

In [24]:
# Value of the first element of w
X = df[df.Make == 'Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates().values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [25]:
X_transpose = X.transpose()
X_transpose

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [49]:
XTX = X_transpose.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [50]:
X_inv = np.linalg.inv(XTX)
X_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [51]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y

[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [53]:
w = np.matmul(X_inv, X_transpose) * y
w

array([[-1.45145106e+00,  2.27554657e-01,  1.71851173e-01,
        -3.55949211e+00,  5.80343386e+00, -2.39406462e+00,
         1.42221660e+00,  3.17391339e+00,  1.20098291e+00],
       [ 9.46982487e+01,  5.89254188e-01,  2.75982449e+00,
         2.16399957e+02, -2.77873207e+02,  1.51207962e+02,
        -5.18727169e+01, -1.48262613e+02, -5.12110350e+01]])

In [56]:
w[0][0]

-1.4514510559958258